### ISSUE TITLE
Hamburger Menu Options Invisible

### ISSUE THREAD

**Issue by danielpopovici745** [mindovermiles262/top-dark-theme#19]
Hey I just recently found this dark theme add on and found the options for the hamburger menu are invisible (I think they are just white). I was hovering over "My Path" with my cursor which is why it appears gray.
![image](https://user-images.githubusercontent.com/57043199/146500547-385bddc2-f690-4ed5-95c6-22b5a0cec89b.png)

**Comment by mindovermiles262** [comment]
Confirmed. I see this too. I'll take a look at it soon

Thanks for reporting this bug :)

**Comment by danielpopovici745** [comment]
No problem! Thanks for the quick fix 😄🔧
