### ISSUE TITLE
Contrast on 404 Page

### ISSUE THREAD

**Issue by ZachPoole** [mindovermiles262/top-dark-theme#24]
Hey just an issue I found with some contrast.
The 404 page needs more contrast for the text.
For this specific page I went to https://www.theodinproject.com/dashboard

![image](https://user-images.githubusercontent.com/46611063/147893161-81af9e87-2bf6-4f56-8880-573bc2e45b87.png)

**Comment by mindovermiles262** [comment]
Hey @ZachPoole ! Thanks for bringing this to my attention. Unfortunatly the blue background is an svg image so not much can be done with that, but I was able to make the grey white so it looks better. This is fixed in v2.2.9 which will be out shortly.

Thanks again
