### ISSUE TITLE
Bug - : Home Page Header and First Section have different shade backgrounds

### ISSUE THREAD

**Issue by ArjunSaili1** [mindovermiles262/top-dark-theme#30]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: links blend in with normal text`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The header on the home page and first section have different shade background while using dark mode. 
<img width="1512" alt="Screen Shot 2022-03-18 at 11 08 26 AM" src="https://user-images.githubusercontent.com/66842156/159030792-3fdb20bf-e6fc-4a90-9cc3-2ab51f6ec5b7.png">

**2. How To Reproduce:**

1. Go to www.theodinproject.com

**3. Expected Behavior:**

1. Go to www.theodinproject.com
2. The header and first section have the same colour background

**4. Desktop/Device:**

- Device: Macbook Pro M1 Pro
- OS: macOS Monterey
- Browser: Chrome
- Version: 99.0.4844.74

**5. Additional Information:**

**Comment by wise-king-sullyman** [comment]
Interesting. I'm not seeing it on my machine but I don't have a Mac to check it on unfortunately.

If anyone else with a Mac can reproduce this issue please drop a comment here.

**Comment by KevinMulhern** [comment]
This has been fixed on the site repo
