### ISSUE TITLE
Complete Lesson hover state

### ISSUE THREAD

**Issue by chico-oliveira** [mindovermiles262/top-dark-theme#9]
Not a big issue but noticed that the hover state for the blue buttons makes the text very difficult to read, could be worth looking into even for accessibility reasons! 

![image](https://user-images.githubusercontent.com/86253998/132498749-f6dc64e2-ee08-4487-9553-bc5ace3a4a88.png)

**Comment by chico-oliveira** [comment]
I've found a similar issue in the grey buttons of the Solutions section of Odin Projects:

![image](https://user-images.githubusercontent.com/86253998/132541660-ca3115ac-a710-4890-9287-b975c47af5f2.png)

**Comment by mindovermiles262** [comment]
Which version are you using? I've just pushed an update and the latest should be v2.2.3

**Comment by chico-oliveira** [comment]
It says I'm using version 2.2.3. Also I'm using firefox dev edition as the browser

**Comment by mindovermiles262** [comment]
Fixed in 2.2.4
